// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {driver} from '../models';
import {main} from '../models';
import {store} from '../models';
import {ai} from '../models';

export function AiChat(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CancelQuery():Promise<void>;

export function ClearHistory():Promise<void>;

export function ClearQueryCache():Promise<void>;

export function Connect(arg1:driver.ConnectionConfig):Promise<main.ConnectionStatus>;

export function DeleteAiConversation(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteHistory(arg1:string):Promise<void>;

export function DeleteSavedQuery(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DiscoverAll():Promise<main.DiscoveryResult>;

export function DryRun(arg1:string):Promise<driver.DryRunResult>;

export function Execute(arg1:string,arg2:number):Promise<driver.QueryResult>;

export function ExportCSV(arg1:string):Promise<string>;

export function ExportExcel(arg1:string):Promise<string>;

export function ExportJSON(arg1:string):Promise<string>;

export function GenerateSampleQueries(arg1:string):Promise<Array<main.SampleQuery>>;

export function GetAiMessages(arg1:string):Promise<Array<store.ChatMessage>>;

export function GetAiProviders():Promise<Array<ai.ProviderInfo>>;

export function GetAiSettings():Promise<main.AiSettings>;

export function GetAvailableDrivers():Promise<Array<string>>;

export function GetCodePaths():Promise<Array<string>>;

export function GetConnectionStatus():Promise<main.ConnectionStatus>;

export function GetHistory(arg1:string,arg2:number,arg3:number):Promise<Array<store.HistoryEntry>>;

export function GetHistoryStats():Promise<store.HistoryStats>;

export function GetQueryBySlug(arg1:string):Promise<store.SavedQuery>;

export function GetTableSchema(arg1:string,arg2:string):Promise<driver.TableInfo>;

export function ListAiConversations():Promise<Array<store.Conversation>>;

export function ListDatabases():Promise<Array<string>>;

export function ListSavedConnections():Promise<Array<store.SavedConnection>>;

export function ListSavedQueries(arg1:string):Promise<Array<store.SavedQuery>>;

export function ListServerDatabases(arg1:driver.ConnectionConfig):Promise<Array<string>>;

export function ListTables(arg1:string):Promise<Array<driver.TableInfo>>;

export function ListTemplates(arg1:string):Promise<Array<store.QueryTemplate>>;

export function OptimizeQuery(arg1:string):Promise<main.OptimizeResult>;

export function ParseConnectionString(arg1:string,arg2:string):Promise<driver.ConnectionConfig>;

export function PickFile(arg1:string):Promise<string>;

export function PickFolder(arg1:string):Promise<string>;

export function PreviewTable(arg1:string,arg2:string,arg3:number):Promise<driver.QueryResult>;

export function RenameAiConversation(arg1:string,arg2:string):Promise<void>;

export function SaveConnection(arg1:driver.ConnectionConfig):Promise<void>;

export function SaveQuery(arg1:string,arg2:string,arg3:string,arg4:string):Promise<store.SavedQuery>;

export function ScanCodeContext(arg1:Array<string>):Promise<main.CodeContext>;

export function SetAiSettings(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetCodePaths(arg1:Array<string>):Promise<void>;

export function TestConnection(arg1:driver.ConnectionConfig):Promise<void>;
