// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AiChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['AiChat'](arg1, arg2, arg3);
}

export function CancelQuery() {
  return window['go']['main']['App']['CancelQuery']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClearQueryCache() {
  return window['go']['main']['App']['ClearQueryCache']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteAiConversation(arg1) {
  return window['go']['main']['App']['DeleteAiConversation'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteSavedQuery(arg1) {
  return window['go']['main']['App']['DeleteSavedQuery'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DiscoverAll() {
  return window['go']['main']['App']['DiscoverAll']();
}

export function DryRun(arg1) {
  return window['go']['main']['App']['DryRun'](arg1);
}

export function Execute(arg1, arg2) {
  return window['go']['main']['App']['Execute'](arg1, arg2);
}

export function ExecuteAsync(arg1, arg2) {
  return window['go']['main']['App']['ExecuteAsync'](arg1, arg2);
}

export function ExplainQuery(arg1) {
  return window['go']['main']['App']['ExplainQuery'](arg1);
}

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function ExportExcel(arg1) {
  return window['go']['main']['App']['ExportExcel'](arg1);
}

export function ExportJSON(arg1) {
  return window['go']['main']['App']['ExportJSON'](arg1);
}

export function GenerateSampleQueries(arg1) {
  return window['go']['main']['App']['GenerateSampleQueries'](arg1);
}

export function GetAiMessages(arg1) {
  return window['go']['main']['App']['GetAiMessages'](arg1);
}

export function GetAiProviders() {
  return window['go']['main']['App']['GetAiProviders']();
}

export function GetAiSettings() {
  return window['go']['main']['App']['GetAiSettings']();
}

export function GetAvailableDrivers() {
  return window['go']['main']['App']['GetAvailableDrivers']();
}

export function GetCodePaths() {
  return window['go']['main']['App']['GetCodePaths']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetHistory'](arg1, arg2, arg3);
}

export function GetHistoryStats() {
  return window['go']['main']['App']['GetHistoryStats']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetQueryBySlug(arg1) {
  return window['go']['main']['App']['GetQueryBySlug'](arg1);
}

export function GetTableSchema(arg1, arg2) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2);
}

export function ListAiConversations() {
  return window['go']['main']['App']['ListAiConversations']();
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function ListSavedConnections() {
  return window['go']['main']['App']['ListSavedConnections']();
}

export function ListSavedQueries(arg1) {
  return window['go']['main']['App']['ListSavedQueries'](arg1);
}

export function ListServerDatabases(arg1) {
  return window['go']['main']['App']['ListServerDatabases'](arg1);
}

export function ListTables(arg1) {
  return window['go']['main']['App']['ListTables'](arg1);
}

export function ListTemplates(arg1) {
  return window['go']['main']['App']['ListTemplates'](arg1);
}

export function OptimizeQuery(arg1) {
  return window['go']['main']['App']['OptimizeQuery'](arg1);
}

export function ParseConnectionString(arg1, arg2) {
  return window['go']['main']['App']['ParseConnectionString'](arg1, arg2);
}

export function PickFile(arg1) {
  return window['go']['main']['App']['PickFile'](arg1);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function PreviewTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewTable'](arg1, arg2, arg3);
}

export function RenameAiConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameAiConversation'](arg1, arg2);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveQuery(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveQuery'](arg1, arg2, arg3, arg4);
}

export function ScanCodeContext(arg1) {
  return window['go']['main']['App']['ScanCodeContext'](arg1);
}

export function ScanCodeFull(arg1) {
  return window['go']['main']['App']['ScanCodeFull'](arg1);
}

export function SetAiSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAiSettings'](arg1, arg2, arg3, arg4);
}

export function SetCodePaths(arg1) {
  return window['go']['main']['App']['SetCodePaths'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
